spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ttb_interview_item4?useSSL=false
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

spring.jpa:
  properties:
    hibernate:
      transaction:
        jta:
          platform: org.hibernate.service.jta.platform.internal.NoJtaPlatform

kafka:
  bootstrap-servers: localhost:9092
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-serializer: org.apache.kafka.common.serialization.StringSerializer
  topic:
    request: crm-request
    update: crm-update
